title: Ardèch'Drôm Dev
email: contact@ardechdromdev.org
description: "Les communautés de développeurs Drôme-Ardéchois se fédèrent"
baseurl: ""
url: "http://www.ardechdromdev.org"
lang: fr
twitter_username: ArdechDromDev
timezone: Europe/Paris
